[project]
name = "serbest-atis-proje"
description = "A basketball free throw prediction game on Stacks blockchain where players predict their shots and earn tokens for correct predictions"
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.basketball-game]
path = "contracts/basketball-game.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
